############################
#     VoidWarp - Config    #
############################

world:
  # mode: The mode to use when the player is in the region (SPAWN/COMMAND/WARP/ESSENTIALS_WARP/HUSKHOME_WARP)
  mode: SPAWN
  # yMin: The Y coordinate at the bottom of the range (Leave empty to have no minimum)
  yMin: -1000
  # yMax: The Y coordinate at the top of the range (Leave empty to have no maximum)
  yMax: 0
  # message: The message that is displayed in chat when you are teleported
  message: "<grey>Teleported to <yellow>%location%</yellow>."
  # commands: Commands ran when in the region (Note: Only valid if mode is "COMMAND") (COMMANDS CURRENTLY ONLY RAN AS PLAYER)
  commands: [ ]
  # warps: A list of warps (Note: Only valid if mode is "WARP", "ESSENTIALS_WARP" OR "HUSKHOME_WARP")
  warps: [ ]
  # whitelist: Sets whether the warps list is a whitelist or blacklist (Note: Only valid if mode is "WARP")
  whitelist: true