name: VoidWarp
version: ${project.version}
main: me.dave.voidwarp.VoidWarp
api-version: 1.19
authors: [ Dav_e_ ]
description: Teleports you to a specific location, runs a command or warps you to the nearest warp when you go above or below a specified Y level.
